---
- name: create shared directory
  file: path={{ shared_path }}/config/initializers owner={{ user }} state=directory

- include: generate_database.yml
#- include: generate_faye_token.yml
#- include: generate_resque.yml
#- include: copy_github_oauth_token.yml
